name: Go

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.20.0"
          check-latest: false

      - name: Build
        run: just build

  gofumpt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ">=1.20.0"
      - name: Install gofumpt
        run: |
          wget https://github.com/mvdan/gofumpt/releases/download/v0.4.0/gofumpt_v0.4.0_linux_amd64
          mv gofumpt_v0.4.0_linux_amd64 gofumpt
          chmod +x gofumpt
          mv gofumpt /usr/local/bin
      - name: Check and format .go files
        run: |
          [ "$(gofumpt -d ./..)" = "" ]
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.20.0"
          check-latest: false
      - name: Tests
        run: go test -v ./...
